### ISSUE TITLE
repeated disconnections in IOS(PocketSocket compression issue)

### ISSUE THREAD

**Issue by shantanubhadoria** [NathanaelA/nativescript-websockets#18]
Good Day,
Thank you for this module. While this module works perfectly fine in my android code, on IOS I am getting constant disconnections, my web socket traffic is reasonably frequent. 

`Socket closed. Reconnecting in 6 seconds Failed to inflate bytes code: 1002`

As I understand this comes from the pocket socket library and its documented in a related library here https://github.com/martijnwalraven/meteor-ios/issues/67

Any quick fix for getting around this?

Cheers!

**Comment by shantanubhadoria** [comment]
This comment https://github.com/martijnwalraven/meteor-ios/issues/67#issuecomment-151309322 suggests disabling _pmdEnabled = NO; in PocketSocket/PSWebSocketDriver.m file
HTH

**Comment by NathanaelA** [comment]
Thanks for the report; I read through that whole list and it does say it should be fixed in v1.00 of pocketSocket -- however based on when I forked the project I believe I forked before this version.   I will need to rebase the two projects to get my back to the same master as they are.     

Just to set expectation; this is a low priority, as I have paid work in my queue which always comes first...

**Comment by NathanaelA** [comment]
I forgot to update this issue a while back; just was going through them today.   I'm using the current latest version of pocketSocket + some patch.   So this should be fixed at this point...
