### ISSUE TITLE
The sending of Protocols support is not fully implemented on both platforms

### ISSUE THREAD

**Issue by emmanuelbuah** [NathanaelA/nativescript-websockets#2]
@NathanaelA when you say "The sending of Protocols support is not fully implemented on both platforms. Do not depend on this; it only partially works.", does that mean WS.send(message) isn't reliable and shouldn't be used? I'm currently working on Meteor ddp client using your plugin and need to reliably send messages to the server.

**Comment by NathanaelA** [comment]
@emmanuelbuah - As for the websocket library itself, it is totally reliable!      The only thing that is not supported is the rarely used special "protocols" special header negotiation.   

The Sending of the **protocols** is a special header negotiation during the initial connection.  You can basically say.  new websocket(server,["VideoA","VideoB", "VideoC"]); and then the server you connect to will see if it has been configured to say it supports VideoA, VideoB, or VideoC.   If it supports any of those the it sends back the name of the first one it supports as the supported protocol.  And everything continues just like normal.    If the server does not support any of the protocol list you send it disconnects with an error message.   The "Protocols" are just a list that you maintain on both sides and it does not actually change any of the traffic at all.      It is a rarely used feature which is why it is not supported very well (a lot of servers don't even support it either).

**Comment by emmanuelbuah** [comment]
Gotcha. Thanks for elaborating.

**Comment by emmanuelbuah** [comment]
@NathanaelA Another question. Is the postinstall.js in the support doing the the same thing the cli does for the platform folder in a plugin. Specifically, can the support folder be renamed to platforms as well as excluding the postinstall.js script. I noticed the struct was a bit different so I was curious if there was any difference.

**Comment by NathanaelA** [comment]
No the postinstall script is needed to setup stuff on android and ios.   The configuration is totally different on both platforms.  On Android you can do a tns library add; on ios; it needs to generate a new (or modified) module map and copy some .h files into a specific folder...

**Comment by NathanaelA** [comment]
If you put in your package.json file a dependency on my plugin -- I think tns will use it fine.
