### ISSUE TITLE
> Awesome -- I'll try and test this today! (Replace PocketSocket with iOS native websockets)

### ISSUE THREAD

**Issue by coolsun** [NathanaelA/nativescript-websockets#91]
> Awesome -- I'll try and test this today!
_Originally posted by @coolsun in https://github.com/NathanaelA/nativescript-websockets/issues/82#issuecomment-864282155_

Related issue posted: https://github.com/edusperoni/nativescript-mqtt/issues/18

Issue: Silently Crashed on connect and Subscribe in ns-mqtt due to PocketSocket issue - not fixable according to [edusperoni](https://github.com/edusperoni)

@NathanaelA, we got stuck by this issue for our IOT app mqtt feature release because mqtt silently crashed on connect/subscribe due to an error in PocketSocket.  There is no other alternative now and mqtt monitoring app seems a great utility for IOT websites like my customer.  Since you have started the work some time ago, do you have an ETA for replacing PocketSocket with iOS native websockets?  Thank you very much!

**Comment by NathanaelA** [comment]
@coolsun - Hi Benjamin, 

At this point my paid contracts are over whelming enough that I haven't had any real time to work on any of the free open source stuff.   If this is a priority, you can contact me and we can arrange a contract job to fix it.   But otherwise, any open source project are always a lower priority than the clients who have paid for work...

**Comment by NathanaelA** [comment]
This is merged into the replacement plugin `@master.technology/websockets`
